#Solution 1: IN
SELECT ROUND(SUM(TIV_2016), 2) TIV_2016
FROM (SELECT TIV_2016 
      FROM insurance
      WHERE (LAT, LON) IN (SELECT LAT, LON FROM insurance GROUP BY 1, 2 HAVING COUNT(*) = 1)
      AND TIV_2015 IN (SELECT TIV_2015 FROM insurance GROUP BY 1 HAVING COUNT(*) > 1))t1;


#Solution 2: window function
SELECT ROUND(SUM(TIV_2016), 2) TIV_2016
FROM (SELECT *, 
      COUNT(*) OVER(PARTITION BY TIV_2015) CT15,
      COUNT(*) OVER(PARTITION BY LAT, LON) LOC
      FROM insurance) t
WHERE CT15 > 1 AND LOC = 1;
